# =============================================================================
# Cross-Platform CI Pipeline (Generic Template)
# =============================================================================
#
# WHAT: Runs tests on Linux, Windows, and macOS to catch platform-specific
#       bugs before they merge to protected branches.
#
# KEY PATTERNS DEMONSTRATED:
#   - Optimized matrix with `include` (not Cartesian product) to reduce jobs
#   - `fail-fast: false` so one platform failure does not cancel others
#   - Conditional coverage collection (one OS only to save time)
#   - Gate job aggregation for branch protection (single required check)
#   - Cross-platform venv activation (Windows vs Unix)
#   - Path-filtered triggers to skip CI on docs-only changes
#   - Concurrency groups with cancel-in-progress
#   - Minimal permissions (principle of least privilege)
#
# HOW TO CUSTOMIZE:
#   - Replace `src/backend/` and `src/frontend/` with your actual paths
#   - Adjust the Python and Node.js versions to match your project
#   - Add or remove OS entries in the matrix `include` list
#   - Set `--cov-fail-under` to your project's minimum coverage threshold
#   - Replace `npm run` commands with your actual test/build commands
#
# REFERENCE: eia-ci-failure-patterns/references/gate-job-pattern.md
#            eia-ci-failure-patterns/references/matrix-optimization.md
# =============================================================================

name: CI

on:
  push:
    branches: [main, develop]
    paths:
      # Only run CI when source code or config actually changes
      # WHY: Avoids wasting CI minutes on docs-only or README changes
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'tsconfig*.json'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'tsconfig*.json'
      - '.github/workflows/ci.yml'

# WHY: If a new commit is pushed to the same PR, cancel the in-flight run
# instead of queuing both. Saves CI minutes and avoids stale results.
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# WHY: Principle of least privilege. CI only needs to read code and actions.
permissions:
  contents: read
  actions: read

jobs:
  # --------------------------------------------------------------------------
  # Python Tests - Optimized Matrix (4 jobs instead of 6)
  # --------------------------------------------------------------------------
  # WHY `include` instead of Cartesian product: A full matrix of 2 Python
  # versions x 3 OSes = 6 jobs. Using `include` we pick only the combos
  # that matter: primary version on all OSes + secondary version on Linux only.
  test-python:
    name: Python (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      # WHY: If macOS fails, we still want to see Linux and Windows results.
      # With fail-fast:true (default), one failure cancels all other jobs.
      fail-fast: false
      matrix:
        include:
          # Primary Python version on ALL platforms for cross-platform coverage
          - os: ubuntu-latest
            python-version: '3.12'
          - os: windows-latest
            python-version: '3.12'
          - os: macos-latest
            python-version: '3.12'
          # Secondary Python version on Linux only for compatibility check
          # WHY: Saves 2 extra jobs (Windows+macOS) that rarely find version issues
          - os: ubuntu-latest
            python-version: '3.13'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # WHY: Create venv for isolation. The activation path differs on Windows.
      - name: Create virtual environment
        shell: bash
        run: python -m venv .venv

      - name: Install dependencies
        shell: bash
        working-directory: src/backend
        run: |
          # Cross-platform venv activation pattern:
          # Windows uses Scripts/, Unix uses bin/
          if [ "$RUNNER_OS" == "Windows" ]; then
            source ../../.venv/Scripts/activate
          else
            source ../../.venv/bin/activate
          fi
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run all tests
        working-directory: src/backend
        shell: bash
        env:
          PYTHONPATH: ${{ github.workspace }}/src/backend
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            source ../../.venv/Scripts/activate
          else
            source ../../.venv/bin/activate
          fi
          # -v: verbose output for CI logs
          # --tb=short: condensed tracebacks (full tracebacks are noisy in CI)
          # -x: stop on first failure (fail fast within this job)
          pytest ../../tests/ -v --tb=short -x

      # WHY: Coverage is expensive and platform-independent. Run it once on
      # Linux with the primary Python version only.
      - name: Run coverage (Linux + primary Python only)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        working-directory: src/backend
        shell: bash
        env:
          PYTHONPATH: ${{ github.workspace }}/src/backend
        run: |
          source ../../.venv/bin/activate
          pytest ../../tests/ -v \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=10  # Set to your project's minimum coverage

      # WHY: Upload coverage to external service for PR decoration and tracking
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          file: ./src/backend/coverage.xml
          # WHY: Don't fail CI if Codecov service is down
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # --------------------------------------------------------------------------
  # Frontend Tests - All Platforms
  # --------------------------------------------------------------------------
  test-frontend:
    name: Frontend (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        working-directory: src/frontend
        # WHY: `ci` is stricter than `install` - uses lockfile exactly,
        # fails if lockfile is out of date. Ensures reproducible builds.
        run: npm ci

      # WHY: Type check catches errors that tests might miss.
      # Run it before tests so type errors surface first.
      - name: Run TypeScript type check
        working-directory: src/frontend
        run: npx tsc --noEmit

      - name: Run unit tests
        working-directory: src/frontend
        run: npm test

      # WHY: Build verifies that the code compiles for production.
      # Catches import errors, missing assets, bundler config issues.
      - name: Build application
        working-directory: src/frontend
        run: npm run build

  # --------------------------------------------------------------------------
  # Gate Job - Single required check for branch protection
  # --------------------------------------------------------------------------
  # WHY: Without a gate job, branch protection must list every matrix job
  # individually. If you add/remove matrix entries, you must update branch
  # protection settings. A gate job aggregates all results into one check.
  ci-complete:
    name: CI Complete
    runs-on: ubuntu-latest
    needs: [test-python, test-frontend]
    # WHY `if: always()`: Without this, the gate job is SKIPPED when any
    # upstream job fails. A skipped job passes branch protection by default,
    # which means broken code can merge. `always()` ensures the gate job
    # runs and explicitly checks for failures.
    if: always()
    steps:
      - name: Check all CI jobs passed
        run: |
          echo "## CI Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Result |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| test-python | ${{ needs.test-python.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| test-frontend | ${{ needs.test-frontend.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Check that ALL upstream jobs succeeded
          if [[ "${{ needs.test-python.result }}" != "success" ]] || \
             [[ "${{ needs.test-frontend.result }}" != "success" ]]; then
            echo "One or more CI jobs failed" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "All CI checks passed" >> $GITHUB_STEP_SUMMARY
