# =============================================================================
# Multi-Language Lint Pipeline (Generic Template)
# =============================================================================
#
# WHAT: Runs parallel language-specific linting jobs (Python + JavaScript/
#       TypeScript) to enforce code style and catch errors early.
#
# KEY PATTERNS DEMONSTRATED:
#   - Parallel language-specific linting jobs
#   - Pinned tool versions with comments about where to sync
#   - Ruff check + Ruff format as separate steps (lint vs formatting)
#   - GitHub annotation output format (`--output-format=github`)
#   - ESLint for JavaScript/TypeScript (alternative: Biome shown in comments)
#   - Gate job aggregation for branch protection
#   - Path-filtered triggers
#   - Concurrency groups with cancel-in-progress
#
# HOW TO CUSTOMIZE:
#   - Replace `src/backend/` and `src/frontend/` with your actual paths
#   - Pin Ruff version to match your .pre-commit-config.yaml or pyproject.toml
#   - Pin ESLint version to match your package.json devDependencies
#   - Add additional linting jobs for Go (golangci-lint), Rust (clippy), etc.
#   - Switch from ESLint to Biome if preferred (see commented alternative)
#
# REFERENCE: eia-ci-failure-patterns/references/linter-configuration.md
#            eia-ci-failure-patterns/references/gate-job-pattern.md
# =============================================================================

name: Lint

on:
  push:
    branches: [main, develop]
    paths:
      # WHY: Only trigger when source code or linter configs change.
      # Avoids wasting CI minutes on unrelated changes.
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/lint.yml'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'        # Ruff config may live here
      - 'ruff.toml'             # Or in a dedicated ruff config
      - '.eslintrc*'            # ESLint config files
      - 'eslint.config.*'       # ESLint flat config
      - 'src/frontend/biome.jsonc'  # If using Biome instead
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/lint.yml'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'ruff.toml'
      - '.eslintrc*'
      - 'eslint.config.*'
      - 'src/frontend/biome.jsonc'

# WHY: Cancel in-flight lint runs for the same PR when new commits arrive.
# Lint results for old commits are worthless once new code is pushed.
concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # --------------------------------------------------------------------------
  # Python Linting with Ruff
  # --------------------------------------------------------------------------
  # WHY Ruff: 10-100x faster than flake8/pylint, replaces both linter and
  # formatter. Single tool, single config, fast feedback.
  python:
    name: Python (Ruff)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # WHY pin version: Ruff versions can introduce new rules or change
      # behavior. Pin to the SAME version as your local dev setup.
      # SYNC WITH: .pre-commit-config.yaml, pyproject.toml [tool.ruff]
      - name: Install Ruff
        run: pip install ruff==0.8.6

      # WHY separate steps: `ruff check` finds logical errors and style
      # violations. `ruff format` checks code formatting. They fail for
      # different reasons and need different fix commands.
      - name: Ruff lint check
        run: |
          # --output-format=github produces GitHub-native annotations
          # WHY: Annotations appear inline on PR diff, making issues easy to spot
          ruff check src/backend/ tests/ --output-format=github

      - name: Ruff format check
        run: |
          # --check: exits non-zero if files would be reformatted (does not modify)
          # --diff: shows what would change, useful for CI logs
          ruff format src/backend/ tests/ --check --diff

  # --------------------------------------------------------------------------
  # JavaScript/TypeScript Linting with ESLint
  # --------------------------------------------------------------------------
  # WHY ESLint: Most widely adopted JS/TS linter with extensive plugin
  # ecosystem. Alternative: Biome (see commented section below).
  typescript:
    name: TypeScript (ESLint)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      # WHY `npm ci`: Uses lockfile exactly for reproducible installs.
      # ESLint and its plugins are installed as devDependencies.
      - name: Install dependencies
        working-directory: src/frontend
        run: npm ci

      # WHY: ESLint catches code quality issues, unused variables,
      # import errors, TypeScript-specific anti-patterns.
      - name: Run ESLint
        working-directory: src/frontend
        run: |
          # --max-warnings=0: Treat warnings as errors in CI
          # WHY: Prevents warning accumulation. Fix warnings before they pile up.
          npx eslint . --max-warnings=0

      # -----------------------------------------------------------------------
      # ALTERNATIVE: Biome (uncomment to use instead of ESLint)
      # WHY Biome: 15-25x faster than ESLint, built-in formatter, zero config.
      # -----------------------------------------------------------------------
      # - name: Setup Biome
      #   uses: biomejs/setup-biome@v2
      #   with:
      #     version: 2.3.11  # SYNC WITH: package.json devDependencies
      #
      # - name: Run Biome
      #   working-directory: src/frontend
      #   run: |
      #     # `biome ci` fails on errors by default; warnings are reported
      #     # but do not block. Use --error-on-warnings to enforce all rules.
      #     biome ci .

  # --------------------------------------------------------------------------
  # Gate Job - Single required check for branch protection
  # --------------------------------------------------------------------------
  # WHY: A single gate job means branch protection rules do not need to list
  # every individual lint job. Add or remove lint jobs without updating settings.
  lint-complete:
    name: Lint Complete
    runs-on: ubuntu-latest
    needs: [python, typescript]
    if: always()
    steps:
      - name: Check lint results
        run: |
          echo "## Lint Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Linter | Result |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Python (Ruff) | ${{ needs.python.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| TypeScript (ESLint) | ${{ needs.typescript.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.python.result }}" != "success" ]] || \
             [[ "${{ needs.typescript.result }}" != "success" ]]; then
            echo "Linting failed" >> $GITHUB_STEP_SUMMARY
            echo "  Python:     ${{ needs.python.result }}"
            echo "  TypeScript: ${{ needs.typescript.result }}"
            exit 1
          fi

          echo "All linting passed" >> $GITHUB_STEP_SUMMARY
